import { siteConfig } from './config';

export interface Location {
  slug: string;
  name: string;
  county: string;
  population: string;
  description: string;
  neighborhoods?: string[];
  zipCodes: string[];
}

export const locations: Location[] = [
  {
    slug: 'addison',
    name: 'Addison',
    county: 'Dallas County',
    population: '16,000',
    description: 'Addison is known for its vibrant restaurant scene and business district. Our plumbers serve both residential and commercial properties throughout Addison with fast, reliable service.',
    neighborhoods: ['Addison Circle', 'Midway Hollow', 'Village on the Parkway'],
    zipCodes: ['75001', '75254'],
  },
  {
    slug: 'allen',
    name: 'Allen',
    county: 'Collin County',
    population: '105,000',
    description: 'Allen is known for its excellent schools and family-friendly neighborhoods. We provide professional plumbing services to homes throughout Allen.',
    neighborhoods: ['Twin Creeks', 'Watters Creek', 'The Village at Allen', 'Allen Station'],
    zipCodes: ['75002', '75013'],
  },
  {
    slug: 'anna',
    name: 'Anna',
    county: 'Collin County',
    population: '16,000',
    description: 'Anna is one of the fastest-growing cities in Collin County. We provide plumbing services to both new construction and established homes in Anna.',
    zipCodes: ['75409'],
  },
  {
    slug: 'argyle',
    name: 'Argyle',
    county: 'Denton County',
    population: '4,500',
    description: 'Argyle offers a rural feel with easy access to the metroplex. We provide plumbing services to homes and equestrian properties throughout Argyle.',
    neighborhoods: ['Harvest', 'The Highlands', 'Canyon Falls'],
    zipCodes: ['76226'],
  },
  {
    slug: 'arlington',
    name: 'Arlington',
    county: 'Tarrant County',
    population: '400,000',
    description: 'Arlington is home to major attractions and diverse neighborhoods. We provide fast, reliable plumbing service throughout the city, from North Arlington to South Arlington.',
    neighborhoods: ['North Arlington', 'South Arlington', 'East Arlington', 'Dalworthington Gardens', 'Pantego'],
    zipCodes: ['76001', '76002', '76006', '76010', '76011', '76012', '76013', '76014', '76015', '76016', '76017', '76018'],
  },
  {
    slug: 'aubrey',
    name: 'Aubrey',
    county: 'Denton County',
    population: '4,500',
    description: 'Aubrey is a growing community with new developments and established ranches. Our plumbers serve all of Aubrey with professional service.',
    zipCodes: ['76227'],
  },
  {
    slug: 'azle',
    name: 'Azle',
    county: 'Tarrant/Parker County',
    population: '13,000',
    description: 'Located near Eagle Mountain Lake, Azle offers lakeside living and suburban comfort. We provide plumbing services to all Azle neighborhoods.',
    zipCodes: ['76020'],
  },
  {
    slug: 'benbrook',
    name: 'Benbrook',
    county: 'Tarrant County',
    population: '24,000',
    description: 'Benbrook is a family-friendly city near Benbrook Lake. Our plumbers provide fast, reliable service to all Benbrook homes and businesses.',
    zipCodes: ['76109', '76116', '76126'],
  },
  {
    slug: 'burleson',
    name: 'Burleson',
    county: 'Johnson/Tarrant County',
    population: '49,000',
    description: 'Burleson combines small-town charm with modern amenities. We serve Burleson homeowners with professional plumbing services.',
    neighborhoods: ['Old Town Burleson', 'Hidden Creek', 'Elk Ridge'],
    zipCodes: ['76028', '76097'],
  },
  {
    slug: 'carrollton',
    name: 'Carrollton',
    county: 'Dallas/Denton County',
    population: '135,000',
    description: 'Carrollton offers a great mix of suburban living with urban amenities. Our team provides expert plumbing service to all Carrollton neighborhoods.',
    neighborhoods: ['Old Downtown Carrollton', 'Castle Hills', 'Indian Creek', 'Josey Ranch'],
    zipCodes: ['75006', '75007', '75010', '75011'],
  },
  {
    slug: 'cedar-hill',
    name: 'Cedar Hill',
    county: 'Dallas County',
    population: '49,000',
    description: 'Cedar Hill is nestled among rolling hills and offers beautiful views of Joe Pool Lake. We provide reliable plumbing services throughout Cedar Hill.',
    neighborhoods: ['Lake Ridge', 'High Pointe', 'Waterford Oaks'],
    zipCodes: ['75104', '75106'],
  },
  {
    slug: 'celina',
    name: 'Celina',
    county: 'Collin/Denton County',
    population: '18,000',
    description: 'Celina is one of the fastest-growing cities in Texas with many new developments. Our plumbers specialize in both new construction and existing homes.',
    neighborhoods: ['Light Farms', 'Mustang Lakes', 'Carter Ranch'],
    zipCodes: ['75009'],
  },
  {
    slug: 'colleyville',
    name: 'Colleyville',
    county: 'Tarrant County',
    population: '27,000',
    description: 'Colleyville features upscale homes and excellent schools. We provide premium plumbing services to Colleyville residents with attention to detail.',
    neighborhoods: ['Montclair', 'Colleyville Downs', 'The Parks of Colleyville'],
    zipCodes: ['76034'],
  },
  {
    slug: 'coppell',
    name: 'Coppell',
    county: 'Dallas/Denton County',
    population: '42,000',
    description: 'Coppell is known for its top-rated schools and family-oriented community. Our plumbers serve Coppell homes with professional, reliable service.',
    neighborhoods: ['Coppell Old Town', 'Riverchase', 'Northlake Woodlands'],
    zipCodes: ['75019', '75099'],
  },
  {
    slug: 'corinth',
    name: 'Corinth',
    county: 'Denton County',
    population: '22,000',
    description: 'Corinth offers suburban living with easy access to Denton and the metroplex. We provide quality plumbing services to all Corinth neighborhoods.',
    zipCodes: ['76208', '76210'],
  },
  {
    slug: 'dallas',
    name: 'Dallas',
    county: 'Dallas County',
    population: '1.3 million',
    description: `As ${siteConfig.city}'s premier plumbing service, we know the unique challenges of Dallas homes — from aging infrastructure in East Dallas to modern builds in Uptown. Our team responds fast across all Dallas neighborhoods.`,
    neighborhoods: ['Uptown', 'Oak Lawn', 'Deep Ellum', 'Bishop Arts', 'Lakewood', 'East Dallas', 'Oak Cliff', 'Preston Hollow', 'Lake Highlands'],
    zipCodes: ['75201', '75204', '75205', '75206', '75214', '75219', '75223', '75226', '75243'],
  },
  {
    slug: 'denton',
    name: 'Denton',
    county: 'Denton County',
    population: '150,000',
    description: 'Home to two major universities, Denton has a vibrant community with diverse housing needs. We service students, families, and businesses throughout Denton.',
    neighborhoods: ['Downtown Denton', 'Robson Ranch', 'Quakertown', 'Vintage Denton'],
    zipCodes: ['76201', '76203', '76205', '76207', '76208', '76209', '76210'],
  },
  {
    slug: 'desoto',
    name: 'DeSoto',
    county: 'Dallas County',
    population: '56,000',
    description: 'DeSoto is a diverse community with well-established neighborhoods. Our plumbers provide fast, reliable service to DeSoto homeowners.',
    neighborhoods: ['Canterbury', 'Thorntree', 'Windmill Hill'],
    zipCodes: ['75115'],
  },
  {
    slug: 'duncanville',
    name: 'Duncanville',
    county: 'Dallas County',
    population: '40,000',
    description: 'Duncanville offers affordable housing and a strong sense of community. We provide professional plumbing services throughout Duncanville.',
    zipCodes: ['75116', '75137'],
  },
  {
    slug: 'fairview',
    name: 'Fairview',
    county: 'Collin County',
    population: '10,000',
    description: 'Fairview features spacious lots and upscale homes. Our plumbers provide premium service to Fairview residents.',
    neighborhoods: ['Gentle Creek', 'Heritage Ranch'],
    zipCodes: ['75069'],
  },
  {
    slug: 'farmers-branch',
    name: 'Farmers Branch',
    county: 'Dallas County',
    population: '37,000',
    description: 'Farmers Branch is conveniently located near major highways and offers great value. We serve all Farmers Branch neighborhoods with reliable plumbing services.',
    neighborhoods: ['Brookhaven', 'Mercer Crossing', 'Valley View'],
    zipCodes: ['75234', '75244'],
  },
  {
    slug: 'flower-mound',
    name: 'Flower Mound',
    county: 'Denton/Tarrant County',
    population: '79,000',
    description: 'Flower Mound is known for its excellent schools and beautiful parks. We provide professional plumbing services to Flower Mound families.',
    neighborhoods: ['Bridlewood', 'Wellington', 'Tour 18', 'Canyon Falls'],
    zipCodes: ['75022', '75028'],
  },
  {
    slug: 'forney',
    name: 'Forney',
    county: 'Kaufman County',
    population: '27,000',
    description: 'Forney is a rapidly growing community east of Dallas. Our plumbers serve both new construction and established homes in Forney.',
    neighborhoods: ['Devonshire', 'Windmill Farms', 'Jackson Crossing'],
    zipCodes: ['75126'],
  },
  {
    slug: 'fort-worth',
    name: 'Fort Worth',
    county: 'Tarrant County',
    population: '935,000',
    description: 'Fort Worth combines Western heritage with modern urban living. Our plumbers serve all Fort Worth neighborhoods, from the Stockyards to the Cultural District.',
    neighborhoods: ['Downtown', 'Stockyards', 'Cultural District', 'TCU Area', 'Southside', 'Arlington Heights', 'Westover Hills'],
    zipCodes: ['76102', '76103', '76104', '76107', '76109', '76110', '76111', '76112', '76116', '76129', '76131', '76132', '76133', '76134', '76135', '76137', '76140', '76148', '76155', '76164', '76177', '76179', '76182', '76244', '76248'],
  },
  {
    slug: 'frisco',
    name: 'Frisco',
    county: 'Collin County',
    population: '220,000',
    description: 'As one of the fastest-growing cities in Texas, Frisco has a mix of new construction and established homes. We provide expert plumbing services for both.',
    neighborhoods: ['Stonebriar', 'Starwood', 'Newman Village', 'Phillips Creek Ranch', 'Richwoods'],
    zipCodes: ['75033', '75034', '75035'],
  },
  {
    slug: 'garland',
    name: 'Garland',
    county: 'Dallas County',
    population: '240,000',
    description: 'Garland features established neighborhoods with mature trees and well-maintained homes. We specialize in both repairs and upgrades for Garland properties.',
    neighborhoods: ['Firewheel', 'Duck Creek', 'Lakewood Heights', 'Eastern Hills'],
    zipCodes: ['75040', '75041', '75042', '75043', '75044', '75045', '75046'],
  },
  {
    slug: 'grand-prairie',
    name: 'Grand Prairie',
    county: 'Dallas/Tarrant County',
    population: '196,000',
    description: 'Grand Prairie offers diverse housing options and family-friendly amenities. We provide reliable plumbing services throughout Grand Prairie.',
    neighborhoods: ['Mira Lagos', 'Mountain Creek', 'Westchester'],
    zipCodes: ['75050', '75051', '75052', '75053', '75054'],
  },
  {
    slug: 'grapevine',
    name: 'Grapevine',
    county: 'Tarrant County',
    population: '54,000',
    description: 'Grapevine is known for its historic Main Street and proximity to DFW Airport. We serve Grapevine residents with professional plumbing services.',
    neighborhoods: ['Historic Downtown', 'Grapevine Lake', 'Silver Lake'],
    zipCodes: ['76051', '76099'],
  },
  {
    slug: 'haltom-city',
    name: 'Haltom City',
    county: 'Tarrant County',
    population: '45,000',
    description: 'Haltom City is a close-knit community northeast of Fort Worth. Our plumbers provide affordable, reliable service to Haltom City homes.',
    zipCodes: ['76117', '76137', '76148'],
  },
  {
    slug: 'haslet',
    name: 'Haslet',
    county: 'Tarrant/Denton County',
    population: '2,000',
    description: 'Haslet is a small but growing community north of Fort Worth. We provide plumbing services to Haslet residents with fast response times.',
    zipCodes: ['76052'],
  },
  {
    slug: 'heath',
    name: 'Heath',
    county: 'Rockwall County',
    population: '9,500',
    description: 'Heath is an upscale lakeside community on Lake Ray Hubbard. Our plumbers provide premium service to Heath homeowners.',
    neighborhoods: ['Heath Golf & Yacht Club', 'Buffalo Creek'],
    zipCodes: ['75032', '75087'],
  },
  {
    slug: 'highland-village',
    name: 'Highland Village',
    county: 'Denton County',
    population: '16,500',
    description: 'Highland Village is an affluent community near Lewisville Lake. We provide quality plumbing services to Highland Village residents.',
    neighborhoods: ['The Shores', 'Highland Shores', 'Lakewood Village'],
    zipCodes: ['75077'],
  },
  {
    slug: 'irving',
    name: 'Irving',
    county: 'Dallas County',
    population: '256,000',
    description: 'From Las Colinas to Valley Ranch, Irving homeowners trust us for reliable plumbing service. We handle everything from emergency repairs to complete repiping.',
    neighborhoods: ['Las Colinas', 'Valley Ranch', 'Irving Arts District', 'Cottonwood Valley'],
    zipCodes: ['75014', '75015', '75016', '75017', '75038', '75039', '75060', '75061', '75062', '75063'],
  },
  {
    slug: 'keller',
    name: 'Keller',
    county: 'Tarrant County',
    population: '48,000',
    description: 'Keller is a family-friendly city with excellent schools and safe neighborhoods. We provide professional plumbing services to Keller homes.',
    neighborhoods: ['Hidden Lakes', 'Marshall Ridge', 'Shady Oaks'],
    zipCodes: ['76244', '76248'],
  },
  {
    slug: 'kennedale',
    name: 'Kennedale',
    county: 'Tarrant County',
    population: '8,500',
    description: 'Kennedale is a small town with a friendly community feel. Our plumbers provide reliable service to Kennedale residents.',
    zipCodes: ['76060'],
  },
  {
    slug: 'lake-worth',
    name: 'Lake Worth',
    county: 'Tarrant County',
    population: '5,000',
    description: 'Lake Worth is situated on the shores of Lake Worth. We provide plumbing services to lakefront properties and homes throughout the city.',
    zipCodes: ['76135'],
  },
  {
    slug: 'lancaster',
    name: 'Lancaster',
    county: 'Dallas County',
    population: '40,000',
    description: 'Lancaster offers affordable living south of Dallas. We provide professional plumbing services to Lancaster homeowners.',
    zipCodes: ['75134', '75146'],
  },
  {
    slug: 'lewisville',
    name: 'Lewisville',
    county: 'Denton County',
    population: '115,000',
    description: 'Located near Lewisville Lake, this city features diverse housing from lakefront properties to family subdivisions. We serve all of Lewisville with fast response times.',
    neighborhoods: ['Castle Hills', 'Valley Vista', 'Lake Park', 'Hebron'],
    zipCodes: ['75029', '75056', '75057', '75067'],
  },
  {
    slug: 'little-elm',
    name: 'Little Elm',
    county: 'Denton County',
    population: '52,000',
    description: 'Little Elm is a lakeside community on Lewisville Lake experiencing rapid growth. Our plumbers serve both new and established Little Elm homes.',
    neighborhoods: ['Union Park', 'Paloma Creek', 'Lakewood Village'],
    zipCodes: ['75068'],
  },
  {
    slug: 'lucas',
    name: 'Lucas',
    county: 'Collin County',
    population: '8,000',
    description: 'Lucas features large lots and upscale country living. We provide premium plumbing services to Lucas homeowners.',
    zipCodes: ['75002', '75098'],
  },
  {
    slug: 'mansfield',
    name: 'Mansfield',
    county: 'Tarrant/Johnson/Ellis County',
    population: '75,000',
    description: 'Mansfield offers excellent schools and family-friendly neighborhoods. Our plumbers serve all of Mansfield with professional service.',
    neighborhoods: ['Walnut Creek', 'Creekwood', 'The Parks at Legacy'],
    zipCodes: ['76063'],
  },
  {
    slug: 'mckinney',
    name: 'McKinney',
    county: 'Collin County',
    population: '200,000',
    description: 'McKinney blends historic charm with modern growth. Whether you have a historic downtown home or a new build in Craig Ranch, we have you covered.',
    neighborhoods: ['Historic Downtown', 'Craig Ranch', 'Stonebridge Ranch', 'Eldorado', 'Trinity Falls'],
    zipCodes: ['75069', '75070', '75071', '75072'],
  },
  {
    slug: 'melissa',
    name: 'Melissa',
    county: 'Collin County',
    population: '14,000',
    description: 'Melissa is a growing community with new developments and a small-town feel. Our plumbers serve Melissa residents with reliable service.',
    zipCodes: ['75454'],
  },
  {
    slug: 'mesquite',
    name: 'Mesquite',
    county: 'Dallas County',
    population: '150,000',
    description: 'Mesquite is known for its rodeo heritage and diverse neighborhoods. We provide professional plumbing services throughout Mesquite.',
    neighborhoods: ['Town East', 'Creek Crossing', 'Mesquite Meadows'],
    zipCodes: ['75149', '75150', '75180', '75181', '75182', '75185'],
  },
  {
    slug: 'murphy',
    name: 'Murphy',
    county: 'Collin County',
    population: '21,000',
    description: 'Murphy is a family-oriented city with excellent schools. We provide quality plumbing services to Murphy homeowners.',
    neighborhoods: ['Maxwell Creek', 'Murphy Village'],
    zipCodes: ['75094'],
  },
  {
    slug: 'north-richland-hills',
    name: 'North Richland Hills',
    county: 'Tarrant County',
    population: '72,000',
    description: 'North Richland Hills offers convenient access to Fort Worth and Dallas. Our plumbers serve NRH residents with fast, reliable service.',
    neighborhoods: ['Smithfield', 'Iron Horse', 'Holiday Heights'],
    zipCodes: ['76180', '76182'],
  },
  {
    slug: 'plano',
    name: 'Plano',
    county: 'Collin County',
    population: '290,000',
    description: 'Plano homes range from established neighborhoods in West Plano to newer developments in the east. We service all Plano areas with fast response times and upfront pricing.',
    neighborhoods: ['West Plano', 'East Plano', 'Legacy', 'Willow Bend', 'Preston Ridge', 'Shops at Legacy'],
    zipCodes: ['75023', '75024', '75025', '75074', '75075', '75093'],
  },
  {
    slug: 'princeton',
    name: 'Princeton',
    county: 'Collin County',
    population: '18,000',
    description: 'Princeton is a fast-growing community northeast of Dallas. We serve Princeton residents with professional plumbing services.',
    zipCodes: ['75407'],
  },
  {
    slug: 'prosper',
    name: 'Prosper',
    county: 'Collin/Denton County',
    population: '33,000',
    description: 'Prosper is an affluent community with beautiful master-planned developments. Our plumbers provide premium service to Prosper homeowners.',
    neighborhoods: ['Windsong Ranch', 'Star Trail', 'Whitley Place', 'Artesia'],
    zipCodes: ['75078'],
  },
  {
    slug: 'richardson',
    name: 'Richardson',
    county: 'Dallas/Collin County',
    population: '120,000',
    description: 'Richardson features a mix of mid-century homes and newer developments near the Telecom Corridor. Our plumbers are experienced with both older and modern plumbing systems.',
    neighborhoods: ['Canyon Creek', 'Prairie Creek', 'Reservation', 'Breckinridge', 'Telecom Corridor'],
    zipCodes: ['75080', '75081', '75082', '75083'],
  },
  {
    slug: 'rockwall',
    name: 'Rockwall',
    county: 'Rockwall County',
    population: '47,000',
    description: 'Rockwall is a lakeside community on Lake Ray Hubbard with beautiful views. We provide professional plumbing services to all Rockwall neighborhoods.',
    neighborhoods: ['The Harbor', 'Chandlers Landing', 'Rush Creek'],
    zipCodes: ['75032', '75087'],
  },
  {
    slug: 'rowlett',
    name: 'Rowlett',
    county: 'Dallas/Rockwall County',
    population: '68,000',
    description: 'Rowlett is situated on Lake Ray Hubbard with great lakefront living. Our plumbers serve Rowlett residents with fast, reliable service.',
    neighborhoods: ['Waterview', 'Bayside', 'Princeton Estates'],
    zipCodes: ['75088', '75089'],
  },
  {
    slug: 'royse-city',
    name: 'Royse City',
    county: 'Rockwall/Hunt County',
    population: '16,000',
    description: 'Royse City is a growing community east of Rockwall. We provide plumbing services to Royse City homes and new developments.',
    zipCodes: ['75189'],
  },
  {
    slug: 'sachse',
    name: 'Sachse',
    county: 'Dallas/Collin County',
    population: '27,000',
    description: 'Sachse is a family-friendly community with excellent schools. Our plumbers provide quality service to Sachse homeowners.',
    zipCodes: ['75048'],
  },
  {
    slug: 'saginaw',
    name: 'Saginaw',
    county: 'Tarrant County',
    population: '24,000',
    description: 'Saginaw is a growing community north of Fort Worth. We provide reliable plumbing services to Saginaw residents.',
    zipCodes: ['76131', '76179'],
  },
  {
    slug: 'southlake',
    name: 'Southlake',
    county: 'Tarrant/Denton County',
    population: '32,000',
    description: 'Southlake is an upscale community known for Southlake Town Square and excellent schools. Our plumbers provide premium service to Southlake homeowners.',
    neighborhoods: ['Southlake Town Square', 'Timarron', 'Shady Oaks'],
    zipCodes: ['76092'],
  },
  {
    slug: 'sunnyvale',
    name: 'Sunnyvale',
    county: 'Dallas County',
    population: '7,500',
    description: 'Sunnyvale features large lots and a rural atmosphere east of Dallas. We provide quality plumbing services to Sunnyvale residents.',
    zipCodes: ['75182'],
  },
  {
    slug: 'terrell',
    name: 'Terrell',
    county: 'Kaufman County',
    population: '18,000',
    description: 'Terrell is a historic community east of Dallas with affordable housing options. Our plumbers serve Terrell residents with reliable service.',
    zipCodes: ['75160'],
  },
  {
    slug: 'the-colony',
    name: 'The Colony',
    county: 'Denton County',
    population: '46,000',
    description: 'The Colony is located on Lewisville Lake with excellent amenities. We provide professional plumbing services to The Colony residents.',
    neighborhoods: ['Stewart Peninsula', 'The Tribute', 'Austin Ranch'],
    zipCodes: ['75056'],
  },
  {
    slug: 'trophy-club',
    name: 'Trophy Club',
    county: 'Denton/Tarrant County',
    population: '13,000',
    description: 'Trophy Club is an upscale planned community known for its golf course. We provide premium plumbing services to Trophy Club homeowners.',
    zipCodes: ['76262'],
  },
  {
    slug: 'university-park',
    name: 'University Park',
    county: 'Dallas County',
    population: '25,000',
    description: 'University Park is an affluent enclave surrounded by Dallas with beautiful homes. We provide premium plumbing services to University Park residents.',
    neighborhoods: ['Snider Plaza', 'Windsor Park', 'Fairfax'],
    zipCodes: ['75205', '75225'],
  },
  {
    slug: 'wylie',
    name: 'Wylie',
    county: 'Collin/Dallas/Rockwall County',
    population: '55,000',
    description: 'Wylie is a fast-growing community east of Plano. We provide professional plumbing services to Wylie homeowners.',
    neighborhoods: ['Inspiration', 'Birmingham Farms', 'The Preserve'],
    zipCodes: ['75098'],
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug);
}

export function getAllLocationSlugs(): string[] {
  return locations.map((l) => l.slug);
}
